spring:
  mongodb:
    embedded:
      version: 3.5.5

kafka:
  enabled: false
  bootstrap-address: ${spring.embedded.kafka.brokers:}
  order-statistic-topic: user-order-statistics
  group-id: book-retail