spring:
  data:
    mongodb:
      host: mongodb
      auto-index-creation: true

kafka:
  enabled: true
  bootstrap-address: kafka:29092
  order-statistic-topic: user-order-statistics
  group-id: book-retail

jwt:
  secretKey: {JWT_SECRETKEY}
  expiryInMs: {JWT_EXPIRYINMS}