spring:
  data:
    mongodb:
      host: localhost
      auto-index-creation: true

kafka:
  enabled: true
  bootstrap-address: localhost:9092
  order-statistic-topic: user-order-statistics
  group-id: book-retail

jwt:
  secretKey: {JWT_SECRETKEY}
  expiryInMs: {JWT_EXPIRYINMS:3600000}